// layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import OnekoScript from "./components/OnekoScript"; // 👈 import the loader
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <OnekoScript /> {/* 👈 this runs your cat script */}
        <div className="fixed top-6 right-10 flex space-x-4"> 
        <Link href="/tutorials" className="px-4 py-2 bg-blue-500 rounded hover:bg-red-600">
          resume
        </Link>
        <Link href="/projects" className="px-4 py-2 bg-yellow-500 rounded hover:bg-yellow-600">
          projects
        </Link> 
        <Link href="/tutorials" className="px-4 py-2 bg-red-500 rounded hover:bg-red-600">
          contact
        </Link>
       
      </div>
      </body>
    </html>
  );
}
